version: "3.8"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/app
      - /app/node_modules/
    command: npm run start
    ports:
      - 4201:4200