version: "3.8"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - 4200:4200