version: "3.8"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./api:/app
      - /app/node_modules/
    command: npm run start:dev
    ports:
      - 3000:3000
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./client:/app
      - /app/node_modules/
    command: npm run start
    ports:
      - 4200:4200