version: "3.8"
services:
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - 5050:80
    env_file:
      - .env
    networks:
      - chit-chat-psql
    volumes:
      - ./servers.json:/pgadmin4/servers.json
  postgres:
    image: postgres:alpine
    ports:
      - 35000:5432
    env_file:
      - .env
    networks:
      - chit-chat-psql
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
networks:
  chit-chat-psql: